kind = "web"
previewPath = "/"
title = "Sistema Classe A"
version = "1.0.0"
id = "artifacts/classe-a"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22053

[services.development]
run = "pnpm --filter @workspace/classe-a run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/classe-a", "run", "build" ]
publicDir = "artifacts/classe-a/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22053"
BASE_PATH = "/"
